
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:Order-System}
  datasource:
    jdbcUrl: jdbc:postgresql://34.42.96.38:5432/crm_db?currentSchema=crm
    username: crmAdmin
    password: crmAdmin
    driver-class-name: org.postgresql.Driver
    allow-pool-suspension: ${DB_ALLOW_POOL_SUSPENSION:true}
    connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
    idle-timeout: ${DB_IDLE_TIMEOUT:6000}
    max-lifetime: ${DB_MAX_LIFETIME:30000}
    leak-detection-threshold: ${DB_LEAK_DETECTION_THRESHOLD:10000}
    pool-name: ${DB_POOL_NAME:SpringBootJPAHikariCP}
    maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
    minimum-idle: ${DB_MIN_IDLE:2}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false




serviceURL:
  ims: https://plusmax-inventory-service-dev-zpl3ofp66a-uc.a.run.app
  cart: https://cart-management-system-dev-ak3ogf6zea-uc.a.run.app
  pms: https://payment-service-dev-ak3ogf6zea-uc.a.run.app
  inbound: https://inbound-service-dev-ak3ogf6zea-uc.a.run.app
  coupon: http://localhost:8079
  vmsService: https://vendor-management-system-stage-fhs4u27yva-uc.a.run.app
  loyalty: http://localhost:8099
  comms: https://communication-preference-management-system-dev-ak3ogf6zea-uc.a.run.app
  company: https://plusmax-company-service-dev-893210385582.us-central1.run.app
  nms: https://notification-management-system-dev-ak3ogf6zea-uc.a.run.app
  user: https://user-service-ak3ogf6zea-uc.a.run.app
  userService: https://user-service-ak3ogf6zea-uc.a.run.app
  wms: https://warehouse-management-system-dev-ak3ogf6zea-uc.a.run.app
  wmsService: https://warehouse-management-system-dev-ak3ogf6zea-uc.a.run.app
  retail: https://retail-management-system-dev-ak3ogf6zea-uc.a.run.app
  retailService: https://retail-management-system-dev-ak3ogf6zea-uc.a.run.app
  pos: https://plusmax-company-service-dev-893210385582.us-central1.run.app
  serviceability: https://serviceability-service-dev-ak3ogf6zea-uc.a.run.app
  cust: https://plusmax-customer-service-dev-893210385582.us-central1.run.app/customer
  customer: https://customer-service-dev-ak3ogf6zea-uc.a.run.app
  cat: https://catalog-management-system-dev-ak3ogf6zea-uc.a.run.app
  cms: https://plusmax-catalog-service-dev-893210385582.us-central1.run.app
  cmsService: https://catalog-management-system-dev-ak3ogf6zea-uc.a.run.app
  logistics: https://logistics-service-dev-ak3ogf6zea-uc.a.run.app
  oms: https://order-management-system-dev-ak3ogf6zea-uc.a.run.app
  report: https://reporting-service-dev-ak3ogf6zea-uc.a.run.app/reporting-service
  purchase: https://purchase-order-system-stage-1064026520425.us-central1.run.app
  omsService: https://order-management-system-dev-ak3ogf6zea-uc.a.run.app
  businessService: https://business-service-dev-ak3ogf6zea-uc.a.run.app
  gateway: https://origin-highway-dev-ak3ogf6zea-uc.a.run.app/proxy

cors-list: >
  https://misogiai-anjani-1999s-projects.vercel.app/
  https://misogiai-anjani-1999s-projects.vercel.app
  https://originhighway-staging-kxyaws5ixa-uc.a.run.app
  https://dev.plusmax.com
  https://dev.plusmax.com/
  https://originhighway-staging-kxyaws5ixa-uc.a.run.app/proxy
  https://plusmax-gateway-service-dev-zpl3ofp66a-uc.a.run.app/
  https://plusmax-gateway-service-dev-zpl3ofp66a-uc.a.run.app
  http://localhost:3000
  http://localhost:3002
  http://localhost:3002/
  http://localhost:3001
  https://highway.palletnow.co  
  https://dev-pos.plusmax.com/
  https://dev-pos.plusmax.com

