
# Application Configuration
app:
  product:
    name: CRM System
  login:
    url: http://localhost:3000/login
  support:
    email: support@company.com
  help:
    center:
      url: http://localhost:3000/help
  company:
    name: Your Company

server:
  port: 8081
  servlet:
    context-path: /crm

spring:
  application:
    name: crm-service
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    com.crm: DEBUG

serviceURL:
  ai-service: http://localhost:8000
  auth-service: http://localhost:8083

# Email Service Configuration
email:
  service:
    url: http://localhost:8000


